[package]
name = "jellything"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
relm4 = { version = "0.6.0", features = ["libadwaita"] }
relm4-icons = { version = "0.6.0", features = ["check-round-outline"] }
reqwest = { version = "0.11.18", features = ["json"] }
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
