icons = [
  "check-round-outline",
  "closed-captioning",
  "eye-open-negative-filled",
  "fast-forward-filled",
  "folder-filled",
  "home-filled",
  "left",
  "library",
  "loupe",
  "movies-and-tv-filled",
  "music-note-2-filled",
  "music-note-single",
  "pause-filled",
  "play-filled",
  "playback-speed",
  "refresh",
  "rewind-filled",
  "right",
  "settings",
  "skip-backward-large",
  "skip-forward-large",
  "star-large",
  "tag-multiple-filled",
  "tv-filled",
  "warning",
]
