// This file was generated by gir (https://github.com/gtk-rs/gir)
// from sys/build
// from sys/gir-files
// DO NOT EDIT

use glib::{translate::*};

#[derive(Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
#[derive(Clone, Copy)]
#[non_exhaustive]
#[doc(alias = "VpmTrackType")]
pub enum TrackType {
    #[doc(alias = "VPM_TRACK_TYPE_VIDEO")]
    Video,
    #[doc(alias = "VPM_TRACK_TYPE_AUDIO")]
    Audio,
    #[doc(alias = "VPM_TRACK_TYPE_SUBTITLE")]
    Subtitle,
#[doc(hidden)]
    __Unknown(i32),
}

#[doc(hidden)]
impl IntoGlib for TrackType {
    type GlibType = ffi::VpmTrackType;

    #[inline]
fn into_glib(self) -> ffi::VpmTrackType {
match self {
            Self::Video => ffi::VPM_TRACK_TYPE_VIDEO,
            Self::Audio => ffi::VPM_TRACK_TYPE_AUDIO,
            Self::Subtitle => ffi::VPM_TRACK_TYPE_SUBTITLE,
            Self::__Unknown(value) => value,
}
}
}

#[doc(hidden)]
impl FromGlib<ffi::VpmTrackType> for TrackType {
    #[inline]
unsafe fn from_glib(value: ffi::VpmTrackType) -> Self {
        skip_assert_initialized!();

match value {
            ffi::VPM_TRACK_TYPE_VIDEO => Self::Video,
            ffi::VPM_TRACK_TYPE_AUDIO => Self::Audio,
            ffi::VPM_TRACK_TYPE_SUBTITLE => Self::Subtitle,
            value => Self::__Unknown(value),
}
}
}
