// This file was generated by gir (https://github.com/gtk-rs/gir)
// from sys/build
// from sys/gir-files
// DO NOT EDIT

use crate::Track;
use glib::translate::*;

glib::wrapper! {
    #[derive(Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
    pub struct TrackList(Boxed<ffi::VpmTrackList>);

    match fn {
        copy => |ptr| ffi::vpm_track_list_copy(mut_override(ptr)),
        free => |ptr| ffi::vpm_track_list_free(ptr),
        type_ => || ffi::vpm_track_list_get_type(),
    }
}

impl TrackList {
    #[doc(alias = "vpm_track_list_is_empty")]
    pub fn is_empty(&self) -> bool {
        unsafe { from_glib(ffi::vpm_track_list_is_empty(self.to_glib_none().0)) }
    }

    #[doc(alias = "vpm_track_list_len")]
    pub fn len(&self) -> u32 {
        unsafe { ffi::vpm_track_list_len(self.to_glib_none().0) }
    }

    #[doc(alias = "vpm_track_list_track")]
    pub fn track(&self, index: u32) -> Option<Track> {
        unsafe { from_glib_full(ffi::vpm_track_list_track(self.to_glib_none().0, index)) }
    }
}
