// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../video_player_mpv_sys/build
// from ../video_player_mpv_sys/gir-files
// DO NOT EDIT

use glib::{object as gobject, prelude::*, translate::*};

glib::wrapper! {
    #[doc(alias = "VpmVideoPlayerMpv")]
    pub struct VideoPlayerMpv(Object<ffi::VpmVideoPlayerMpv, ffi::VpmVideoPlayerMpvClass>) @extends gtk::GLArea, gtk::Widget, gobject::InitiallyUnowned, @implements gtk::Accessible, gtk::Buildable, gtk::ConstraintTarget;

    match fn {
        type_ => || ffi::vpm_video_player_mpv_get_type(),
    }
}

impl VideoPlayerMpv {
    #[doc(alias = "vpm_video_player_mpv_new")]
    pub fn new() -> VideoPlayerMpv {
        assert_initialized_main_thread!();
        unsafe { gtk::Widget::from_glib_none(ffi::vpm_video_player_mpv_new()).unsafe_cast() }
    }
}

impl Default for VideoPlayerMpv {
    fn default() -> Self {
        Self::new()
    }
}
