#!/usr/bin/env bash

set -e

export DIST="$1"
export SOURCE_ROOT="$2"

cd "$SOURCE_ROOT"
# Remove mold linker config, we don't need it for dist
rm "$DIST"/.cargo/config.toml
cargo vendor >"$DIST/.cargo/config"
sed -i 's/^directory = ".*"/directory = "vendor"/g' "$DIST/.cargo/config"
mv vendor "$DIST"
