// This file was generated by gir (https://github.com/gtk-rs/gir)
// from build
// from gir-files
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "VpmVideoPlayerMpvClass", sizeof(VpmVideoPlayerMpvClass), alignof(VpmVideoPlayerMpvClass));
    return 0;
}
