[options]
library = "Vpm"
version = "0.0"
min_cfg_version = "1.0"
target_path = "."
girs_directories = ["build/", "gir-files/"]
work_mode = "sys"
single_version_file = true
external_libraries = ["GLib", "Gtk", "Gdk", "GObject"]
